{
 "title": ".NET Applications",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "role", "label": "Role", "query": { "query": "label_values(up, role)" } },
   { "name": "percentile", "label": "Percentile", "query": "0.50, 0.75, 0.95, 0.99" },
   { "name": "legend_width", "query": "250" },
   { "name": "frequency", "query": "15s" }
  ]
 },
 "panels": [
  {
   "title": "Message Delivery Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(consumer_received_message_latency_ms_bucket{role=~\"$role\"}[$__rate_interval])) by (le, instance, role))",
     "legendFormat": "{{instance}} - {{role}}"
    },
    {
     "expr": "histogram_quantile($percentile, sum(rate(producer_message_sending_latency_ms_bucket{role=~\"$role\"}[$__rate_interval])) by (le, role))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Messages Delivered Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance, role)(rate(consumer_received_messages_total{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{role}}"
    },
    {
     "expr": "sum by(role)(rate(producer_messages_sent_total{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  { "title": ".NET Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "description": "Number of garbage collections that have occurred since process start.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (generation, role)(rate(process_runtime_dotnet_gc_collections_count{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}} - {{generation}}"
    }
   ]
  },
  {
   "title": "GC Heap Size",
   "type": "timeseries",
   "description": "The heap size (including fragmentation), as observed during the latest garbage collection. The value will be unavailable until at least one garbage collection has occurred.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (role, generation)(avg_over_time(process_runtime_dotnet_gc_heap_size_bytes{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}} - {{generation}}"
    }
   ]
  },
  {
   "title": "GC Heap Fragmentation Size",
   "type": "timeseries",
   "description": "The heap fragmentation, as observed during the latest garbage collection. The value will be unavailable until at least one garbage collection has occurred.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (role, generation)(avg_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}} - {{generation}}"
    }
   ]
  },
  {
   "title": "GC Memory",
   "type": "timeseries",
   "description": "Allocated - count of bytes allocated on the managed GC heap since the process start. .NET objects are allocated from this heap. Object allocations from unmanaged languages such as C/C++ do not use this heap.\nCommitted - the amount of committed virtual memory for the managed GC heap, as observed during the latest garbage collection. Committed virtual memory may be larger than the heap size because it includes both memory for storing existing objects (the heap size) and some extra memory that is ready to handle newly allocated objects in the future. The value will be unavailable until at least one garbage collection has occurred.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (role, generation)(rate(process_runtime_dotnet_gc_allocations_size_bytes{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}} - allocated"
    },
    {
     "expr": "sum by (role, generation)(rate(process_runtime_dotnet_gc_committed_memory_size_bytes{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}} - committed"
    }
   ]
  },
  {
   "title": "Lock Contention Count",
   "type": "timeseries",
   "description": "The number of times there was contention when trying to acquire a monitor lock since the process start. Monitor locks are commonly acquired by using the lock keyword in C#, or by calling Monitor.Enter() and Monitor.TryEnter().",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (role)(rate(process_runtime_dotnet_monitor_lock_contention_count{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Thread Pool Size",
   "type": "timeseries",
   "description": "The number of thread pool threads that currently exist.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (role)(process_runtime_dotnet_thread_pool_threads_count{role=~\"$role\"})",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Thread Pool Completed Items",
   "type": "timeseries",
   "description": "The number of work items that have been processed by the thread pool since the process start.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (role)(rate(process_runtime_dotnet_thread_pool_completed_items_count{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "JIT Compilation Time",
   "type": "timeseries",
   "description": "The amount of time the JIT compiler has spent compiling methods since the process start.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by(role)(rate(process_runtime_dotnet_jit_compilation_time_ns{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "JIT Compilation Count",
   "type": "timeseries",
   "description": "The number of times the JIT compiler compiled a method since the process start. The JIT compiler may be invoked multiple times for the same method to compile with different generic parameters, or because tiered compilation requested different optimization settings.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(role)(rate(process_runtime_dotnet_jit_methods_compiled_count{role=~\"$role\"}[$__rate_interval]))",
     "legendFormat": "{{role}}"
    }
   ]
  }
 ]
}