global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    metrics_path: /metrics
    static_configs:
    - targets: ['api.app.domain:80']
      labels:
        role: 'api'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
