plugin: aws_ec2
regions:
  - "eu-central-1"
hostnames:
  - private-ip-address
  - private-dns-name
leading_separator: False
keyed_groups:
  - key: tags.role.split(":")
include_filters:
  - instance-state-name: running
  - tag:project: api_pg_bench
exclude_filters:
  - tag:role: bastion
