---
docker_ecr_auth:
- region: "{{ aws_region }}"
  url: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"

docker_containers:
- name: producer
  image: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/api"
  tag: "{{ image_tag }}"
  published_ports:
  - "80:80"
  env:
    ASPNETCORE_ENVIRONMENT: "Production"
    ASPNETCORE_URLS: "http://+:80"
    ConnectionStrings__Default: "Host=db.app.domain;Port=5432;Database=postgres;Username=postgres;Password=postgres"
