docker_volumes:
- name: postgres

docker_containers:
- name: producer
  image: "postgres"
  tag: "15.2"
  recreate: "no"
  published_ports:
  - "5432:5432"
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_DB: "postgres"
  volumes:
  - "postgres:/var/lib/postgresql/data"
