---
docker_ecr_auth:
- region: "{{ aws_region }}"
  url: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"

docker_containers:
- name: k6
  image: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/k6"
  tag: "{{ image_tag }}"
  auto_remove: "yes"
  restart_policy: "no"
  command: "run --tag testid={{ '%Y%m%d%H%M%S' | strftime(ansible_date_time.epoch) }} -o experimental-prometheus-rw /app/create-transactions-test.js"
  env:
    API_HOSTNAME: "http://api.app.domain"
    K6_PROMETHEUS_RW_SERVER_URL: "http://monitor.app.domain:9090/api/v1/write"
    K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM: "true"
